Document: codetest-sl
Title: Debian codetest-sl Manual
Author: <insert document author here>
Abstract: This manual describes what codetest-sl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/codetest-sl/codetest-sl.sgml.gz

Format: postscript
Files: /usr/share/doc/codetest-sl/codetest-sl.ps.gz

Format: text
Files: /usr/share/doc/codetest-sl/codetest-sl.text.gz

Format: HTML
Index: /usr/share/doc/codetest-sl/html/index.html
Files: /usr/share/doc/codetest-sl/html/*.html
